baseURL: 'https://www.philenflo.nl/'
languageCode: nl
title: Phil & Flo
theme: philflo
paginate: 100
defaultContentLanguage: nl
timeout: 280000
markup:
    goldmark:
        renderer:
          unsafe: true

  