baseURL: 'https://freshtv.netlify.app/'
languageCode: nl
title: FreshTV
theme: freshtv
paginate: 100
defaultContentLanguage: nl
markup:
    goldmark:
        renderer:
          unsafe: true
permalinks:
  pages: /:slug/
  