baseURL: 'https://philflo.netlify.app/'
languageCode: nl
title: Phil & Flo
theme: philflo
paginate: 100
defaultContentLanguage: nl
markup:
    goldmark:
        renderer:
          unsafe: true
permalinks:
  pages: /:slug/
  