baseURL: 'https://philenflo.nl/'
languageCode: nl
title: Phil & Flo
theme: philflo
paginate: 100
defaultContentLanguage: nl
disableLanguages: ["en", "de"]
markup:
    goldmark:
        renderer:
          unsafe: true
permalinks:
  pages: /:slug/
  