nl:
  languageName: Nederland (Nederlands)
  languageCode: nl
  weight: 1
  permalinks:
    members: over-ons/:slug/ 
    pages: :slug/
    cases: portfolio/:slug/
    solutions: oplossingen/:slug/
en:
  languageName: International (English)
  languageCode: en
  weight: 2
