footer:
  title: Say Hello!
  phonenumber:
    formatted: 085 273 8331
    raw: "+31852738331"
  social:
    title: Stay in the loop
    facebook: https://www.facebook.com/philenflo
    twitter: no
    instagram: https://www.instagram.com/freshtvnl
