footer:
  title: Say Hello!
  phonenumber:
    formatted: 085 273 8331
    raw: "+31852738331"
  social:
    title: Stay in the loop
    linkedin: https://www.instagram.com/freshtvnl
    facebook: https://www.facebook.com/philenflo
    instagram: https://www.instagram.com/freshtvnl
    youtube: https://www.instagram.com/freshtvnl
